name: Run

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '*.psm1'
      - '*.ps1'
      - '.github/workflows/run.yaml'
  schedule:
    - cron: "00 1 * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        shell: pwsh
        run: ./src/main.ps1 | Out-File artists.md

      - name: Push file
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add ./artists.md
          git commit -am "[Automated changes] Update artists"
          git push
        shell: pwsh