name: Run

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '*.psm1'
      - '*.ps1'

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Run"
        env:
          API_KEY: ${{ secret.API_KEY }}
        shell: pwsh
        run: ./main.ps1